In [1]:
import numpy as np
from numpy.linalg import matrix_power
import pydtmc
from pydtmc import MarkovChain

In [11]:
p_v = 0.3
q = 0.5
r = 0.2
#P = np.array([[p + r/2,0,q + r/2],[0,q+r/2,p+r/2],[p/2+r/4,q/2+r/4,p/2+q/2+r/2]])
p = [[p_v + r/2,0,q + r/2],[0,q+r/2,p_v+r/2],[p_v/2+r/4,q/2+r/4,p_v/2+q/2+r/2]]
p

[[0.4, 0, 0.6], [0, 0.6, 0.4], [0.2, 0.3, 0.5]]

In [12]:
mc = MarkovChain(p, ['A', 'B', 'C'])
print(mc)


DISCRETE-TIME MARKOV CHAIN
 SIZE:           3
 RANK:           2
 CLASSES:        1
  > RECURRENT:   1
  > TRANSIENT:   0
 ERGODIC:        YES
  > APERIODIC:   YES
  > IRREDUCIBLE: YES
 ABSORBING:      NO
 MONOTONE:       NO
 REGULAR:        YES
 REVERSIBLE:     YES
 SYMMETRIC:      NO



In [21]:
print(mc.expected_transitions(10**10))
#print(mc.expected_rewards)

[[6.40e+08 0.00e+00 9.60e+08]
 [0.00e+00 2.16e+09 1.44e+09]
 [9.60e+08 1.44e+09 2.40e+09]]


In [18]:
mc.first_passage_probabilities(1,mc)

NameError: name 'first_passage_probabilities' is not defined

In [47]:
#mc.mean_number_visits()
#mc.to_matrix()
#mc.transition_probability('B','A')
#mc.simulate(10, initial_state=None, final_state=None, output_indices=False, seed=None)
#mc.hitting_probabilities()
#mc.conditional_probabilities('B')
#mc.absorption_probabilities()
lista = mc.simulate(10**5)
a = 0
b = 0
c = 0
for i in lista:
    if i == 'A':
        a += 1
    elif i == 'B':
        b += 1
    elif i == 'C':
        c += 1
print(f'a: {a/len(lista)}, b:{b/len(lista)}, c:{c/len(lista)}')
print(a,b,c)

a: 0.15728842711572885, b:0.36538634613653864, c:0.47732522674773253
15729 36539 47733
